package mail

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

// The generated lookup tables.
//
// All three are written from the panel's own record on every reconcile, whole,
// and never merged with what was there. That is what makes a deleted mailbox
// stop existing: a table the panel appended to would accumulate every address
// the host had ever had, and "delete" would be the one operation that did not
// work.
//
// Every value written here has been through validation before it arrived, and
// the formats are line-oriented and space-delimited — so a value containing a
// space or a newline would not corrupt the table, it would silently *become* a
// different entry. buildLine refuses those rather than trusting that the
// validation upstream can never change.

// mapEntry is one line of a lookup table.
type mapEntry struct {
	key   string
	value string
}

// renderMap builds a Postfix lookup table.
//
// Sorted by key, which matters for a reason beyond tidiness: the file is
// compared against the one already on disk to decide whether the daemons need
// reloading, and an unsorted file would differ on every reconcile and reload a
// mail server every minute.
func renderMap(header string, entries []mapEntry) ([]byte, error) {
	sorted := make([]mapEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].key != sorted[j].key {
			return sorted[i].key < sorted[j].key
		}
		return sorted[i].value < sorted[j].value
	})

	var out strings.Builder
	out.WriteString("# " + header + "\n")
	out.WriteString("# Generated by JotHost Panel. Every line here comes from the panel's\n")
	out.WriteString("# own record and this file is rewritten whole on each change:\n")
	out.WriteString("# an edit made here is lost, silently, at the next reconcile.\n")
	for _, entry := range sorted {
		if err := checkField(entry.key); err != nil {
			return nil, err
		}
		if err := checkField(entry.value); err != nil {
			return nil, err
		}
		out.WriteString(entry.key)
		out.WriteString(" ")
		out.WriteString(entry.value)
		out.WriteString("\n")
	}
	return []byte(out.String()), nil
}

// checkField refuses a value that would not survive the file format.
//
// A last line of defence rather than the first. Every one of these values has
// been validated already — this exists because the file being written is read
// by a process running as root, and the cost of being wrong once is an entry
// that quietly means something other than what the panel recorded.
func checkField(value string) error {
	if value == "" {
		return fmt.Errorf("a lookup table entry may not be empty")
	}
	if strings.ContainsAny(value, " \t\r\n#") {
		return fmt.Errorf(
			"a lookup table entry may not contain whitespace or a comment character: %q", value)
	}
	return nil
}

// buildMaps renders the three Postfix lookup tables from the desired state.
func (p *Provider) buildMaps(desired Desired) (domains, mailboxes, aliases []byte, err error) {
	var domainEntries, mailboxEntries, aliasEntries []mapEntry

	for _, domain := range desired.Domains {
		if !domain.Active {
			// An inactive domain is absent from every table, which is what
			// makes the server answer "we do not accept mail for that domain"
			// rather than accepting it and having nowhere to put it.
			continue
		}
		// The value is unused by Postfix for a domain table — only the
		// presence of the key matters — so it carries something a human
		// reading the file can use.
		domainEntries = append(domainEntries, mapEntry{key: domain.Name, value: "virtual"})

		for _, box := range domain.Mailboxes {
			if !box.Active {
				continue
			}
			address := box.Address(domain.Name)
			// The value is the Maildir path relative to the mail root. Postfix
			// does not deliver into it — Dovecot does, over LMTP — but the
			// entry has to exist for the recipient to be accepted at all, and
			// a path here keeps the file meaningful to anybody reading it.
			mailboxEntries = append(mailboxEntries, mapEntry{
				key:   address,
				value: domain.Name + "/" + box.LocalPart + "/",
			})
		}

		for _, alias := range domain.Aliases {
			if !alias.Active {
				continue
			}
			aliasEntries = append(aliasEntries, mapEntry{
				key:   alias.Source + "@" + domain.Name,
				value: alias.Destination,
			})
		}

		// The catch-all, last, because it is the entry that swallows
		// everything the others did not match.
		//
		// "@domain" is Postfix's syntax for it, and it applies only after every
		// specific address in the table has failed to match — so a catch-all
		// never shadows a real mailbox.
		if domain.CatchAll != "" {
			aliasEntries = append(aliasEntries, mapEntry{
				key:   "@" + domain.Name,
				value: domain.CatchAll,
			})
		}
	}

	if domains, err = renderMap("Domains this host accepts mail for", domainEntries); err != nil {
		return nil, nil, nil, err
	}
	if mailboxes, err = renderMap("Mailboxes", mailboxEntries); err != nil {
		return nil, nil, nil, err
	}
	if aliases, err = renderMap("Forwarders and catch-alls", aliasEntries); err != nil {
		return nil, nil, nil, err
	}
	return domains, mailboxes, aliases, nil
}

// buildPasswdFile renders Dovecot's passwd-file.
//
// The format is colon-delimited: user:password:uid:gid:gecos:home:shell:extra.
// The panel writes the same uid and gid for every mailbox — see the package
// comment on why there is one vmail account rather than thousands — and puts
// the per-mailbox settings in the extra fields, where Dovecot reads the quota
// rule and the mail location from.
//
// A colon in any field would end it early and give the next one a value the
// panel did not write, which is why the local part is validated to a character
// set that cannot contain one, and why every field is checked again here.
func buildPasswdFile(desired Desired, uid, gid int, mailRoot string) ([]byte, error) {
	type entry struct {
		address string
		line    string
	}
	var entries []entry

	for _, domain := range desired.Domains {
		if !domain.Active {
			continue
		}
		for _, box := range domain.Mailboxes {
			address := box.Address(domain.Name)
			if !box.Active {
				// A suspended mailbox is absent from the file, so it cannot
				// authenticate. Its Maildir is untouched: the mail is still
				// there and comes back the moment the mailbox is reactivated,
				// which is the difference between suspending and deleting.
				continue
			}
			if strings.ContainsAny(box.PasswordHash, ":\r\n") {
				return nil, fmt.Errorf(
					"the stored password hash for %s is not a hash the panel wrote", address)
			}
			if err := checkPasswdField(address); err != nil {
				return nil, err
			}

			home := mailRoot + "/" + domain.Name + "/" + box.LocalPart
			// The extra fields. userdb_ prefixed values are what Dovecot uses
			// after authentication succeeds: where the mail is, and how much of
			// it is allowed.
			extras := []string{
				"userdb_mail=maildir:" + home,
			}
			if box.QuotaMB > 0 {
				// storage=NM is Dovecot's own syntax. A mailbox at its limit
				// rejects new mail at LMTP time with a permanent error, so the
				// sender is told — rather than the message being accepted and
				// dropped, which is the failure mode that loses mail silently.
				extras = append(extras,
					"userdb_quota_rule=*:storage="+strconv.Itoa(box.QuotaMB)+"M")
			}

			line := strings.Join([]string{
				address,
				box.PasswordHash,
				strconv.Itoa(uid),
				strconv.Itoa(gid),
				"", // gecos: nothing worth putting here
				home,
				"", // shell: a mailbox is not a login to this machine
				strings.Join(extras, " "),
			}, ":")
			entries = append(entries, entry{address: address, line: line})
		}
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].address < entries[j].address })

	var out strings.Builder
	out.WriteString("# Dovecot passwd-file, generated by JotHost Panel.\n")
	out.WriteString("# Rewritten whole on every change: an edit made here is lost.\n")
	out.WriteString("# Contains password hashes. It is mode 0640 and group-owned by the\n")
	out.WriteString("# mail account, because Dovecot's auth worker reads it unprivileged.\n")
	for _, e := range entries {
		out.WriteString(e.line)
		out.WriteString("\n")
	}
	return []byte(out.String()), nil
}

// checkPasswdField refuses a value that would break the passwd-file format.
func checkPasswdField(value string) error {
	if strings.ContainsAny(value, ":\r\n") {
		return fmt.Errorf("a mailbox field may not contain a colon or a line break: %q", value)
	}
	return nil
}

// compile runs postmap over a lookup table.
//
// Only for the indexed formats. texthash is read as it stands, which is why it
// is the fallback: there is no compiled copy to go stale.
func (p *Provider) compile(ctx context.Context, mapType, path string) error {
	if !needsPostmap(mapType) {
		return nil
	}
	if !p.runner.Available(CommandPostmap) {
		return fmt.Errorf(
			"%w: this host has no postmap, which the %s lookup tables need",
			ErrUnavailable, mapType)
	}
	result, err := p.runner.Run(ctx, CommandPostmap, mapType+":"+path)
	if err != nil {
		return wrap("compile the lookup table "+path, err)
	}
	if !result.Succeeded() {
		return fmt.Errorf("compile the lookup table %s: %s",
			path, firstLine(result.Stderr, result.Stdout))
	}
	return nil
}

// ensureAliasDatabase compiles the host's local alias file if it has not been.
//
// Not one of the panel's own tables — this is the distribution's
// /etc/postfix/aliases, which several of them ship uncompiled. The symptom is
// an error in the mail log on every single SMTP connection, which buries the
// entries that matter, and it is the first thing anybody sees when they look at
// why mail is not working.
//
// A failure here is logged and not fatal: it is somebody else's file, this host
// delivers virtually, and refusing to configure mail because a legacy alias
// table could not be built would be the panel getting its priorities wrong.
func (p *Provider) ensureAliasDatabase(ctx context.Context) {
	if !p.runner.Available(CommandPostalias) {
		return
	}
	result, err := p.runner.Run(ctx, CommandPostconf, "-h", "alias_database")
	if err != nil || !result.Succeeded() {
		return
	}
	for _, entry := range strings.Split(strings.TrimSpace(result.Stdout), ",") {
		entry = strings.TrimSpace(entry)
		kind, path, found := strings.Cut(entry, ":")
		if !found || path == "" || kind == "texthash" {
			continue
		}
		if _, err := os.Stat(path); err != nil {
			// No source file: nothing to compile, and nothing wrong.
			continue
		}
		suffix := "." + kind
		if kind == "hash" {
			suffix = ".db"
		}
		if _, err := os.Stat(path + suffix); err == nil {
			continue
		}
		if result, err := p.runner.Run(ctx, CommandPostalias, entry); err != nil || !result.Succeeded() {
			p.log.Warn("could not compile the host's local alias database",
				"database", entry)
		}
	}
}
