package mail

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Autoresponders, and the one genuinely dangerous piece of text in this phase.
//
// A vacation message is written by a customer and ends up inside a Sieve
// script, which the mail server executes for every message that arrives. Sieve
// quotes strings exactly the way C does: a bare double quote ends the string,
// and everything after it is script rather than text. So a subject line of
//
//	Away until Monday"; discard; #
//
// would, without escaping, be a mailbox that silently deletes its own mail.
//
// There are three layers against that and they are all here on purpose:
//
//  1. validate.AutoresponderSubject and AutoresponderBody refuse the control
//     characters no escaping makes safe.
//  2. sieveString escapes the two characters the format defines as special.
//  3. Every generated script is compiled before it is installed. A script that
//     does not compile is one Dovecot skips at delivery time in silence — so
//     the compile is both a syntax check and the proof that what was generated
//     is what was intended.
//
// The third is the one that would catch a mistake in the first two.

// buildSieve renders one mailbox's vacation script.
func buildSieve(address string, responder Autoresponder) []byte {
	var out strings.Builder

	out.WriteString("# Autoresponder for " + sieveComment(address) + "\n")
	out.WriteString("# Generated by JotHost Panel. Rewritten whole on every change.\n")
	out.WriteString("require [\"vacation\"];\n\n")

	out.WriteString("vacation\n")
	// How long before the same sender gets another copy. Never zero: a reply to
	// every message includes a reply to somebody else's vacation reply, and two
	// mailboxes can then write to each other until one of them is full.
	fmt.Fprintf(&out, "  :days %d\n", responder.IntervalDays)
	// The addresses this mailbox answers for. Without it, Sieve only replies
	// when the message was addressed to the login address itself — so mail that
	// arrived through a forwarder gets no reply, which is exactly the mail an
	// away message is for.
	fmt.Fprintf(&out, "  :addresses [%s]\n", sieveString(address))
	fmt.Fprintf(&out, "  :subject %s\n", sieveString(responder.Subject))
	fmt.Fprintf(&out, "  %s;\n", sieveString(responder.Body))

	return []byte(out.String())
}

// sieveString renders a Go string as a Sieve quoted string.
//
// Two characters are special and both are escaped: the backslash first, because
// escaping it after the quote would double-escape the escapes just added.
func sieveString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	// A multi-line body is legal inside a quoted string in Sieve; the line
	// breaks are kept as they are, which is what makes a paragraph arrive as a
	// paragraph.
	return `"` + escaped + `"`
}

// sieveComment makes a value safe to put in a comment.
//
// A comment runs to the end of the line, so a newline in one would end it and
// leave the rest as script. Nothing reaching here should contain one — the
// validation refuses it — and this is the second lock on the same door.
func sieveComment(value string) string {
	replacer := strings.NewReplacer("\r", " ", "\n", " ")
	return replacer.Replace(value)
}

// applySieve writes and compiles the vacation scripts, and removes the ones
// that no longer belong to anybody.
//
// Removal matters as much as writing: a script left behind for a deleted
// mailbox is dormant until somebody creates a mailbox with the same address, at
// which point their mail starts auto-replying with a message written by
// somebody else.
func (p *Provider) applySieve(ctx context.Context, desired Desired, uid, gid int) (bool, error) {
	wanted := map[string]bool{}
	changed := false

	for _, domain := range desired.Domains {
		if !domain.Active {
			continue
		}
		for _, box := range domain.Mailboxes {
			responder := box.Autoresponder
			if responder == nil || !responder.Active || !box.Active {
				continue
			}
			address := box.Address(domain.Name)
			path := p.paths.SieveScript(domain.Name, box.LocalPart)
			wanted[filepath.Base(path)] = true
			// The compiled form sits beside the source with a .svbin
			// extension. It is Dovecot's own artefact; the panel keeps track of
			// it only so that removing a script removes its compiled copy too.
			wanted[filepath.Base(path)+"bin"] = true
			wanted[strings.TrimSuffix(filepath.Base(path), ".sieve")+".svbin"] = true

			content := buildSieve(address, *responder)
			same, err := fileMatches(path, content)
			if err != nil {
				return changed, err
			}
			if same {
				continue
			}
			// 0640, owned by the mail account: Dovecot reads it as the mail
			// user at delivery, and it holds text a customer wrote.
			if err := writeFile(path, content, 0o640, uid, gid); err != nil {
				return changed, err
			}
			if err := p.compileSieve(ctx, path); err != nil {
				// A script that will not compile must not be left in place:
				// Dovecot would ignore it silently and the panel would report
				// an autoresponder that never fires.
				if removeErr := os.Remove(path); removeErr != nil && !os.IsNotExist(removeErr) {
					p.log.Warn("could not remove a Sieve script that failed to compile",
						"path", path, "error", removeErr)
				}
				return changed, err
			}
			changed = true
		}
	}

	removed, err := p.pruneSieve(wanted)
	if err != nil {
		return changed, err
	}
	return changed || removed, nil
}

// pruneSieve removes scripts for mailboxes that no longer have one.
func (p *Provider) pruneSieve(wanted map[string]bool) (bool, error) {
	entries, err := os.ReadDir(p.paths.SieveDir())
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read the Sieve directory: %w", err)
	}

	removed := false
	for _, entry := range entries {
		if entry.IsDir() || wanted[entry.Name()] {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".sieve") && !strings.HasSuffix(name, ".svbin") {
			// Something the panel did not put here. Leaving it alone is right:
			// this directory is the panel's, but deleting an unknown file is
			// how a tool destroys something somebody needed.
			continue
		}
		if err := os.Remove(filepath.Join(p.paths.SieveDir(), name)); err != nil {
			return removed, fmt.Errorf("remove the Sieve script %s: %w", name, err)
		}
		removed = true
	}
	return removed, nil
}

// compileSieve compiles a script, which is both a syntax check and the form
// Dovecot actually executes.
//
// Without a compiled copy Dovecot compiles the script itself at delivery time
// and writes the result beside it — as the mail user, into a directory it may
// not be able to write. The failure is a delivery that works and an
// autoresponder that does not fire, with a line in a log nobody is reading.
func (p *Provider) compileSieve(ctx context.Context, path string) error {
	if !p.runner.Available(CommandSievec) {
		// No compiler is not a failure to compile. Dovecot falls back to
		// compiling at delivery, which usually works; what is lost is the
		// syntax check, so the panel says so rather than claiming the script
		// was verified.
		p.log.Warn("this host has no sievec, so autoresponder scripts are not checked before use",
			"script", path)
		return nil
	}
	result, err := p.runner.Run(ctx, CommandSievec, path)
	if err != nil {
		return wrap("compile the autoresponder script", err)
	}
	if !result.Succeeded() {
		return fmt.Errorf("%w: the autoresponder script was rejected: %s",
			ErrInvalidConfig, firstLine(result.Stderr, result.Stdout))
	}
	return nil
}

// fileMatches reports whether a file already holds exactly this content.
//
// Every generated file goes through it, and the reason is not efficiency. A
// reconcile that rewrote every file would restart the mail server every time it
// ran — dropping every connected IMAP client, on a schedule — because the
// panel's own writes would look like a change. Comparing first is what makes a
// reconcile that changes nothing do nothing.
func fileMatches(path string, content []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	return string(existing) == string(content), nil
}

// parseQueue reads `postqueue -j`, which emits one JSON object per queued
// message.
//
// Parsed by hand rather than with encoding/json, for one reason: the output is
// a stream of objects rather than an array, so a decoder would have to be
// driven message by message anyway, and the two fields wanted here are a number
// and a count. What is deliberately not done is parsing the recipients —
// reading a mail queue is not reading mail, and the panel has no business
// building a list of who this host is corresponding with.
func parseQueue(output string) (count, oldestSeconds int) {
	var oldestArrival int64
	for _, line := range strings.Split(output, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "{") {
			continue
		}
		count++
		arrival := jsonNumberField(trimmed, "arrival_time")
		if arrival > 0 && (oldestArrival == 0 || arrival < oldestArrival) {
			oldestArrival = arrival
		}
	}
	if count == 0 || oldestArrival == 0 {
		return count, 0
	}
	age := nowUnix() - oldestArrival
	if age < 0 {
		age = 0
	}
	return count, int(age)
}

// jsonNumberField pulls one numeric field out of a JSON object on a single
// line.
func jsonNumberField(line, field string) int64 {
	marker := `"` + field + `":`
	index := strings.Index(line, marker)
	if index < 0 {
		return 0
	}
	rest := line[index+len(marker):]
	end := 0
	for end < len(rest) && (rest[end] >= '0' && rest[end] <= '9') {
		end++
	}
	if end == 0 {
		return 0
	}
	value, err := strconv.ParseInt(rest[:end], 10, 64)
	if err != nil {
		return 0
	}
	return value
}
